# Generated by Django 4.1.3 on 2022-11-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildings_number', models.IntegerField(blank=True, null=True)),
                ('street', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50)),
                ('module_duaration', models.IntegerField()),
                ('class_room', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageType', models.CharField(max_length=30)),
                ('qrCodeno', models.URLField(default='https://www.google.pl/', max_length=255)),
                ('admitionDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('destination', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('R', 'Register'), ('P', 'Pending'), ('D', 'DONE'), ('S', 'SEND')], default='P', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.IntegerField()),
                ('product', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_api.addressdetails')),
                ('id_suppliers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_api.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_api.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('address_details', models.ManyToManyField(to='wms_api.addressdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('modules', models.ManyToManyField(to='wms_api.modules')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('P1', 'Package1'), ('P2', 'Package2'), ('P3', 'Package3'), ('P4', 'Package4'), ('P5', 'Package5'), ('P6', 'Package6')], default='P1', max_length=45)),
                ('QR_code', models.URLField(default='https://www.google.pl/', max_length=255)),
                ('category', models.CharField(default='Phones', max_length=30)),
                ('package', models.ManyToManyField(to='wms_api.package')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_type', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField()),
                ('order_col', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_api.user')),
                ('user_address_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_api.addressdetails')),
            ],
        ),
    ]
