# Generated by Django 4.1.3 on 2022-11-25 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='wms_api.package'),
        ),
    ]
