# Generated by Django 4.1.3 on 2022-11-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('packageType', models.CharField(max_length=30)),
                ('qrCodeno', models.URLField(max_length=255)),
                ('admitionDate', models.DateTimeField()),
                ('destination', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
